/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.softcont.prsftmaven.vista;

import com.softcont.prsftmaven.modelo.DAOISesion;
import com.softcont.prsftmaven.modelo.DAOProducto;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Sena1
 */
public final class VProductos extends javax.swing.JFrame {

    DAOProducto modelo;

    public VProductos() throws InstantiationException, IllegalAccessException {
        initComponents();
    }

    public int getcantProducto() {
        return (int) jSpcantidad.getValue();
    }

    public String getCategoria() {
        return (String) jcCategoria.getSelectedItem();
    }

    public String getRuta() {
        return vRuta.getText();
    }

    public void limpiarCampos() {
        txtNombre.setText(null);
        txtPrecioCompra.setText(null);
        vRuta.setText(null);
        jLimagen.setIcon(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPtxtFields = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtPrecioCompra = new javax.swing.JTextField();
        jSpcantidad = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jcCategoria = new javax.swing.JComboBox<>();
        btnCrearCategoria = new javax.swing.JButton();
        btnACategoria = new javax.swing.JButton();
        txtPrecioVenta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPbotones = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jPTabla = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPimgProducto = new javax.swing.JPanel();
        imgPanel = new javax.swing.JPanel();
        btnBuscarImagen = new javax.swing.JButton();
        jLimagen = new javax.swing.JLabel();
        btnCambiarimagen = new javax.swing.JButton();
        jLruta = new javax.swing.JLabel();
        vRuta = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtbuscar = new org.jdesktop.swingx.JXSearchField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestionar Producto");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.gray);
        setResizable(false);

        jPtxtFields.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Informacion del Producto"));

        jLabel1.setText("Codigo:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Stock.");

        jLabel4.setText("Precio de Venta:");

        txtCodigo.setEnabled(false);

        txtPrecioCompra.setEnabled(false);
        txtPrecioCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioCompraKeyTyped(evt);
            }
        });

        jSpcantidad.setModel(new javax.swing.SpinnerNumberModel());
        jSpcantidad.setEnabled(false);

        jLabel6.setText("Categoria:");

        btnCrearCategoria.setText("Crear Categoria");

        btnACategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flechax16.png"))); // NOI18N
        btnACategoria.setBorder(null);
        btnACategoria.setContentAreaFilled(false);
        btnACategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnACategoria.setFocusable(false);
        btnACategoria.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flechax16_press.png"))); // NOI18N

        txtPrecioVenta.setEnabled(false);
        txtPrecioVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioVentaKeyTyped(evt);
            }
        });

        jLabel5.setText("Precio de Compra:");

        javax.swing.GroupLayout jPtxtFieldsLayout = new javax.swing.GroupLayout(jPtxtFields);
        jPtxtFields.setLayout(jPtxtFieldsLayout);
        jPtxtFieldsLayout.setHorizontalGroup(
            jPtxtFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPtxtFieldsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPtxtFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPtxtFieldsLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(btnCrearCategoria)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPtxtFieldsLayout.createSequentialGroup()
                        .addGroup(jPtxtFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPtxtFieldsLayout.createSequentialGroup()
                                .addGroup(jPtxtFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addGroup(jPtxtFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPtxtFieldsLayout.createSequentialGroup()
                                .addGroup(jPtxtFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPtxtFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPtxtFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtPrecioCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                        .addComponent(txtPrecioVenta)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPtxtFieldsLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jcCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnACategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPtxtFieldsLayout.setVerticalGroup(
            jPtxtFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPtxtFieldsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPtxtFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPtxtFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPtxtFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPtxtFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPtxtFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSpcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(34, 34, 34)
                .addGroup(jPtxtFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPtxtFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jcCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnACategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(btnCrearCategoria)
                .addContainerGap())
        );

        jPbotones.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Gestion de Productos"));

        btnRegistrar.setText("Registrar");

        btnNuevo.setText("Nuevo");

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPbotonesLayout = new javax.swing.GroupLayout(jPbotones);
        jPbotones.setLayout(jPbotonesLayout);
        jPbotonesLayout.setHorizontalGroup(
            jPbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPbotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnActualizar)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addGap(18, 18, 18)
                .addComponent(btnNuevo)
                .addContainerGap())
        );
        jPbotonesLayout.setVerticalGroup(
            jPbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPbotonesLayout.createSequentialGroup()
                .addGroup(jPbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar)
                    .addComponent(btnNuevo))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        jPTabla.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Productos Registados"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Cantidad", "Precio de Compra", "Precio de venta", "Categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPTablaLayout = new javax.swing.GroupLayout(jPTabla);
        jPTabla.setLayout(jPTablaLayout);
        jPTablaLayout.setHorizontalGroup(
            jPTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTablaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPTablaLayout.setVerticalGroup(
            jPTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTablaLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPimgProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Imagen Producto"));

        imgPanel.setBackground(new java.awt.Color(255, 255, 255));
        imgPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        imgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuscarImagen.setText("Buscar Imagen");
        btnBuscarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarImagenActionPerformed(evt);
            }
        });
        imgPanel.add(btnBuscarImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        jLimagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLimagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Drop-Files-Here-extra_1.png"))); // NOI18N
        jLimagen.setToolTipText("Agregar Imagen");
        imgPanel.add(jLimagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 280));

        btnCambiarimagen.setText("Cambiar imagen");
        btnCambiarimagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarimagenActionPerformed(evt);
            }
        });

        jLruta.setText("Ruta:");

        javax.swing.GroupLayout jPimgProductoLayout = new javax.swing.GroupLayout(jPimgProducto);
        jPimgProducto.setLayout(jPimgProductoLayout);
        jPimgProductoLayout.setHorizontalGroup(
            jPimgProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPimgProductoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPimgProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCambiarimagen, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPimgProductoLayout.createSequentialGroup()
                        .addGroup(jPimgProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPimgProductoLayout.createSequentialGroup()
                                .addComponent(jLruta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPimgProductoLayout.setVerticalGroup(
            jPimgProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPimgProductoLayout.createSequentialGroup()
                .addGroup(jPimgProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPimgProductoLayout.createSequentialGroup()
                        .addComponent(imgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLruta))
                    .addComponent(vRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCambiarimagen)
                .addGap(26, 26, 26))
        );

        jPanel1.setBackground(new java.awt.Color(133, 188, 68));

        txtbuscar.setToolTipText("Buscar Producto");
        txtbuscar.setLayoutStyle(org.jdesktop.swingx.JXSearchField.LayoutStyle.MAC);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPimgProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPbotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(66, 66, 66)
                        .addComponent(jPtxtFields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPimgProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPbotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPtxtFields, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addComponent(jPTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarImagenActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setDialogTitle("Abrir Archivo");
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Formatos de Archivos de Imagen(*.PNG;*.JPG;*.JPEG)", "jpg", "jpeg", "png");
        fc.setFileFilter(filtro);
        int seleccion = fc.showOpenDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            try {
                File abre = fc.getSelectedFile();
                String ruta = abre.getPath();
                Image foto = getToolkit().getImage(ruta);
                foto = foto.getScaledInstance(jLimagen.getWidth(), jLimagen.getHeight(), Image.SCALE_DEFAULT);
                File carpeta = new File("ImgProductos");
                carpeta.mkdirs();
                if (carpeta.isDirectory()) {

                }
                jLimagen.setIcon(new ImageIcon(foto));
                vRuta.setText(ruta);
                btnBuscarImagen.setVisible(false);
                btnCambiarimagen.setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(VProductos.class.getName()).log(Level.OFF, null, ex);
            }
        }

    }//GEN-LAST:event_btnBuscarImagenActionPerformed

    private void btnCambiarimagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarimagenActionPerformed
        JFileChooser fc = new JFileChooser();
        BufferedImage bmp = null;
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setDialogTitle("Abrir Archivo");
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Formatos de Archivos de Imagen(*.PNG;*.JPG;*.JPEG)", "jpg", "jpeg", "png");
        fc.setFileFilter(filtro);
        int seleccion = fc.showOpenDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File abre = fc.getSelectedFile();
            String ruta = abre.getPath();
            Image foto = getToolkit().getImage(ruta);
            foto = foto.getScaledInstance(jLimagen.getWidth(), jLimagen.getHeight(), Image.SCALE_SMOOTH);
            jLimagen.setIcon(new ImageIcon(foto));
            vRuta.setText(ruta);
            btnBuscarImagen.setVisible(false);
            btnCambiarimagen.setVisible(true);
        }
    }//GEN-LAST:event_btnCambiarimagenActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int fila = jTable1.getSelectedRow();

        if (fila >= 0) {

            try {
                String cod = jTable1.getValueAt(fila, 0).toString();
                String nom = jTable1.getValueAt(fila, 1).toString();
                String cat = jTable1.getValueAt(fila, 5).toString();
                String img = jTable1.getValueAt(fila, 6).toString();
               
                if (jTable1.getValueAt(fila, 2)== null && jTable1.getValueAt(fila, 3)==null && jTable1.getValueAt(fila, 4)==null) {
                    txtCodigo.setText(cod);
                    txtNombre.setText(nom);
                    vRuta.setText(img);
                    jcCategoria.setSelectedItem(cat);
                }else{
                    String cantidad = jTable1.getValueAt(fila, 2).toString();
                    String precioCompra = jTable1.getValueAt(fila, 3).toString();
                    String precioVenta = jTable1.getValueAt(fila, 4).toString();
                    int cant = Integer.parseInt(cantidad);
                    txtCodigo.setText(cod);
                    txtNombre.setText(nom);
                    txtPrecioVenta.setText(precioVenta);
                    txtPrecioCompra.setText(precioCompra);
                    jSpcantidad.setValue(cant);
                    jcCategoria.setSelectedItem(cat);
                    vRuta.setText(img);
                }
                

                
                Image foto = getToolkit().getImage(img);
                foto = foto.getScaledInstance(jLimagen.getWidth(), jLimagen.getHeight(), Image.SCALE_DEFAULT);
                jLimagen.setIcon(new ImageIcon(foto));
                switch (new DAOISesion().getTpUsuario()) {
                    case "Secretaria(o)":
                        btnBuscarImagen.setVisible(false);
                        btnCambiarimagen.setVisible(true);
                        new com.softcont.prsftmaven.controlador.ControladorProductos(this).desbloquear();
                        btnEliminar.setEnabled(false);
                        break;
                    case "Vendedor":
                        btnBuscarImagen.setVisible(false);
                        btnCambiarimagen.setVisible(false);
                        new com.softcont.prsftmaven.controlador.ControladorProductos(this).bloquear();
                        btnRegistrar.setEnabled(false);
                        break;
                    default:
                        btnBuscarImagen.setVisible(false);
                        btnCambiarimagen.setVisible(true);
                        new com.softcont.prsftmaven.controlador.ControladorProductos(this).desbloquear();
                        break;
                }
            } catch (InstantiationException | IllegalAccessException | SQLException ex) {
                Logger.getLogger(VProductos.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Elija una fila...llene la Tabla");
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        try {
            int resp = JOptionPane.showConfirmDialog(this, "¿Desea modificar producto?", "Modificar", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (JOptionPane.OK_OPTION == resp) {
                String nomp = txtNombre.getText();
                String codp = txtCodigo.getText();
                String preciop = txtPrecioVenta.getText();
                String precioCompra = txtPrecioCompra.getText();
                int cantp = getcantProducto();
                String cat = getCategoria();
                String Ruta = getRuta();
                //System.out.println(getRuta());
                modelo = new DAOProducto();
                switch (Ruta) {
                    case "no imagen":
                        String ruta = "no imagen";
                        modelo.modificarProducto(codp, nomp, cat, ruta);
                        modelo.numeros(txtCodigo);
                        modelo.cargar(jTable1);
                        limpiarCampos();
                        break;
                    default:
                        FileInputStream archivofoto;
                        archivofoto = new FileInputStream(getRuta());
                        modelo.modificarProducto(codp, nomp, cat, Ruta, archivofoto);
                        modelo.numeros(txtCodigo);
                        modelo.cargar(jTable1);
                        limpiarCampos();
                        break;
                }
            }

        } catch (HeadlessException | InstantiationException | IllegalAccessException | FileNotFoundException ex) {
            Logger.getLogger(VProductos.class.getName()).log(Level.OFF, null, ex);
            JOptionPane.showMessageDialog(rootPane, "Error" + ex.getMessage());
        }

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int resp = JOptionPane.showConfirmDialog(this, "¿Desea eliminar producto?", "Eliminar", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (JOptionPane.OK_OPTION == resp) {
            try {
                modelo = new DAOProducto();
                if (modelo.EliminarProd(txtCodigo.getText())==true) {
                    modelo.cargar(jTable1);
                    limpiarCampos();
                }else{
                    limpiarCampos();
                    btnEliminar.setEnabled(false);
                    btnRegistrar.setEnabled(true);
                    btnNuevo.setEnabled(false);
                    btnActualizar.setEnabled(false);
                    txtPrecioVenta.setText("");
                    jSpcantidad.setValue(0);
                    modelo.numeros(txtCodigo);
                }
                
                
            } catch (InstantiationException | IllegalAccessException ex) {
                Logger.getLogger(VProductos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtPrecioVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioVentaKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtPrecioVentaKeyTyped

    private void txtPrecioCompraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioCompraKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtPrecioCompraKeyTyped

    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            JFrame.setDefaultLookAndFeelDecorated(true);
            JDialog.setDefaultLookAndFeelDecorated(true);
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        new VProductos().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnACategoria;
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton btnBuscarImagen;
    public javax.swing.JButton btnCambiarimagen;
    public javax.swing.JButton btnCrearCategoria;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnNuevo;
    public javax.swing.JButton btnRegistrar;
    private javax.swing.JPanel imgPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLimagen;
    public javax.swing.JLabel jLruta;
    private javax.swing.JPanel jPTabla;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPbotones;
    private javax.swing.JPanel jPimgProducto;
    private javax.swing.JPanel jPtxtFields;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JSpinner jSpcantidad;
    public javax.swing.JTable jTable1;
    public javax.swing.JComboBox<String> jcCategoria;
    public javax.swing.JTextField txtCodigo;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtPrecioCompra;
    public javax.swing.JTextField txtPrecioVenta;
    private org.jdesktop.swingx.JXSearchField txtbuscar;
    public javax.swing.JLabel vRuta;
    // End of variables declaration//GEN-END:variables
}
